services:
  bear-trak-backend:
    image: kortuga/bear-trak-backend:latest
    container_name: bear-trak-backend
    restart: always
    build:
      context: .
      platforms:
        - "linux/amd64"
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
