services:
  go-server:
    image: index.docker.io/kortuga/bear-trak-backend:latest
    restart: always
    build:
      context: ./go-server
      dockerfile: ../docker/go/Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "3000:3000"

  otp:
    restart: always
    build:
      context: ./otp
      dockerfile: ../docker/otp/Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "8080:8080"
