services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=koppe.development@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  go-server:
    image: ghcr.io/benkoppe/bear-trak-go:${GIT_COMMIT_HASH:-latest}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.go.loadbalancer.server.port=3000"
      - "traefik.http.routers.go.rule=Host(`beartrakapi.thekoppe.com`)"
      - "traefik.http.routers.go.entrypoints=websecure"
      - "traefik.http.routers.go.tls.certresolver=myresolver"
      - "org.opencontainers.image.source=https://github.com/benkoppe/bear-trak-backend"
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    build:
      context: ./go-server
      dockerfile: ../go-server/Dockerfile
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  otp:
    image: ghcr.io/benkoppe/bear-trak-otp:${GIT_COMMIT_HASH:-latest}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.otp.loadbalancer.server.port=8080"
      - "traefik.http.routers.otp.rule=Host(`transit.thekoppe.com`)"
      - "traefik.http.routers.otp.entrypoints=websecure"
      - "traefik.http.routers.otp.tls.certresolver=myresolver"
      - "org.opencontainers.image.source=https://github.com/benkoppe/bear-trak-backend"
    build:
      context: ./otp
      dockerfile: ../otp/Dockerfile
      platforms:
        - "linux/amd64"
    deploy:
      update_config:
        order: stop-first

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    external: true
