name: Pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write
  contents: read

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push `go-server` image
        uses: docker/build-push-action@v6
        with:
          context: ./go-server
          file: go-server/Dockerfile
          push: true
          tags: |
            ghcr.io/benkoppe/bear-trak-go:latest
            ghcr.io/benkoppe/bear-trak-go:${{ github.sha }}

      - name: Build and push `otp` image
        uses: docker/build-push-action@v6
        with:
          context: ./otp
          file: otp/Dockerfile
          push: true
          tags: |
            ghcr.io/benkoppe/bear-trak-otp:latest
            ghcr.io/benkoppe/bear-trak-otp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Stack deploy
        uses: serversideup/github-action-docker-swarm-deploy@v3
        with:
          docker_compose_file_path: -c docker-stack.yml
          ssh_deploy_private_key: "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}"
          ssh_remote_hostname: beartrakssh.thekoppe.com
          registry: "ghcr.io"
          registry-username: ${{ github.actor }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          stack_name: bear-trak
        env:
          GIT_COMMIT_HASH: "${{ github.sha }}"
          CLOUDFLARE_DNS_API_TOKEN: "${{ secrets.CLOUDFLARE_DNS_API_TOKEN }}"
